##### Where is the data? #####
gisaid_input: path/to/gisaid_export
omitted_file: path/to/omitted.txt
uk_input: /cephfs/covid/bham/artifacts/published/elan.latest.consensus.fasta
uk_metadata: /cephfs/covid/bham/artifacts/published/majora.latest.metadata.tsv 
output_path: /cephfs/covid/bham/raccoon-dog/ 

##### GISAID parsing flags #####
gisaid_download_flags: --exclude_uk

##### Filter thresholds #####
min_covg: 95
min_length: 29000

##### Mapping reference #####
reference_fasta: reference.fasta

##### Trim coordinates #####
trim_start: 265
trim_end: 29674

