##### Where is the data? #####
previous_gisaid_fasta: /cephfs/covid/bham/raccoon-dog/2020-04-24_rerun/publish/GISAID/gisaid.full.2020-04-24.fasta
previous_gisaid_metadata: /cephfs/covid/bham/raccoon-dog/2020-04-24_rerun/publish/GISAID/gisaid.full.2020-04-24.with_spangolin123.csv
previous_omitted_file: /cephfs/covid/bham/raccoon-dog/resources/omissions.txt
gisaid_mask_file: /cephfs/covid/bham/raccoon-dog/resources/mask.txt

previous_uk_fasta: /cephfs/covid/bham/raccoon-dog/2020-04-24_rerun/publish/COG/cog_alignment.public.fasta
previous_uk_metadata: /cephfs/covid/bham/raccoon-dog/2020-04-24_rerun/publish/COG/cog_metadata.full.with_spangolin123.csv

latest_gisaid_json: /cephfs/covid/bham/raccoon-dog/2020-05-01/input/export.json
latest_uk_fasta: /cephfs/covid/bham/raccoon-dog/2020-05-01/input/elan.20200501.consensus.fasta
latest_uk_metadata: /cephfs/covid/bham/artifacts/published/latest/majora.20200501.metadata.tsv

output_path: /cephfs/covid/bham/raccoon-dog/2020-05-01/analysis
publish_path: /cephfs/covid/bham/raccoon-dog/2020-05-01/publish
export_path: /cephfs/covid/bham/raccoon-dog/2020-05-01/publish/phylogenetics


##### Filter thresholds #####
min_covg: 95
min_length: 29000

##### Mapping reference #####
reference_fasta: ~/git/grapevine/reference.fasta

##### Trim coordinates #####
trim_start: 265
trim_end: 29674

##### File of SNPs to search for #####
snps: /cephfs/covid/bham/raccoon-dog/resources/snps.csv

##### File of lineages to split by #####
lineage_splits: /cephfs/covid/bham/raccoon-dog/2020-05-01/input/lineage_splits.csv

##### Guide tree #####
guide_tree: /cephfs/covid/bham/raccoon-dog/2020-05-01/input/lineage_representatives.tree

##### Date #####
date:

##### Working directory #####
cwd:

##### Webhook to push to #####
webhook:
