##### Where is the data? #####
previous_gisaid_fasta:
previous_gisaid_metadata:
previous_omitted_file: /cephfs/covid/bham/raccoon-dog/resources/omissions.txt
gisaid_mask_file: /cephfs/covid/bham/raccoon-dog/resources/mask.txt

previous_uk_fasta:
previous_uk_metadata:

latest_gisaid_json:
latest_uk_fasta:
latest_uk_metadata:

output_path: analysis
publish_path: publish
export_path: publish/phylogenetics

##### global lineage definitions #####
global_lineages:

##### Filter thresholds #####
min_covg: 93
min_length: 29000

##### Mapping reference #####
reference_fasta: /cephfs/covid/bham/climb-covid19-jacksonb/git/grapevine/reference.fasta

##### Trim coordinates #####
trim_start: 265
trim_end: 29674

##### Files of variants to search for #####
snps: /cephfs/covid/bham/raccoon-dog/resources/snps.csv
dels: /cephfs/covid/bham/raccoon-dog/resources/dels.csv

##### File of lineages to split by #####
lineage_splits:

##### Guide tree #####
guide_tree: /cephfs/covid/bham/raccoon-dog/resources/graft_guide.tree

##### Date #####
date:

##### Working directory #####
cwd:

##### Webhook to push to #####
webhook:

##### report latex template #####
latex_template:
