##### Where is the data? #####
gisaid_input: path/to/gisaid_export
omitted_file: path/to/omitted.txt
uk_input: path/to/uk/sequences
output_path: analysis 

##### Filter thresholds #####
min_covg: 95
min_length: 29000

##### Mapping reference #####
reference_fasta: reference.fasta

##### Trim coordinates #####
trim_start: 265
trim_end: 29674

