##### Where is the data? #####
previous_gisaid_fasta: /cephfs/covid/bham/raccoon-dog/previous/GISAID/gisaid.fasta
previous_gisaid_metadata: /cephfs/covid/bham/raccoon-dog/previous/GISAID/gisaid.csv
previous_omitted_file: /cephfs/covid/bham/raccoon-dog/previous/GISAID/omissions.txt
previous_uk_fasta: /cephfs/covid/bham/raccoon-dog/previous/COG/cog.tsv
previous_uk_metadata: /cephfs/covid/bham/raccoon-dog/previous/COG/cog.tsv
latest_gisaid_json: GISAID/export.json
latest_uk_fasta: /cephfs/covid/bham/artifacts/published/elan.latest.consensus.fasta
latest_uk_metadata: /cephfs/covid/bham/artifacts/published/majora.latest.metadata.tsv
output_path:

##### GISAID parsing flags #####
gisaid_flags: --exclude-uk --exclude-undated

##### Filter thresholds #####
min_covg: 95
min_length: 29000

##### Mapping reference #####
reference_fasta: "reference.fasta"

##### Trim coordinates #####
trim_start: 265
trim_end: 29674

