##### Where is the data? #####
previous_gisaid_fasta: /cephfs/covid/bham/raccoon-dog/2020-04-24_rerun/publish/GISAID/gisaid.full.2020-04-24.fasta
previous_gisaid_metadata: /cephfs/covid/bham/raccoon-dog/2020-04-24_rerun/publish/GISAID/gisaid.full.2020-04-24.with_spangolin123.csv
previous_omitted_file: /cephfs/covid/bham/raccoon-dog/resources/omissions.txt
gisaid_mask_file: /cephfs/covid/bham/raccoon-dog/resources/mask.txt

previous_uk_fasta: /cephfs/covid/bham/raccoon-dog/previous/COG/cog.fasta
previous_uk_metadata: /cephfs/covid/bham/raccoon-dog/previous/COG/cog.csv

latest_gisaid_json: /cephfs/covid/bham/raccoon-dog/2020-05-01/GISAID/export.json
latest_uk_fasta: /cephfs/covid/bham/artifacts/published/elan.latest.consensus.fasta
latest_uk_metadata: /cephfs/covid/bham/artifacts/published/majora.latest.metadata.tsv

output_path: /cephfs/covid/bham/raccoon-dog/2020-05-01/analysis
publish_path: /cephfs/covid/bham/raccoon-dog/2020-05-01/publish

##### Filter thresholds #####
min_covg: 95
min_length: 29000

##### Mapping reference #####
reference_fasta: /cephfs/covid/bham/climb-covid19-jacksonb/git/grapevine/reference.fasta

##### Trim coordinates #####
trim_start: 265
trim_end: 29674

##### File of lineages to split by #####
lineage_splits: input/lineage_splits.csv

##### Webhook to push to #####
webhook:
