##### Where is the data? #####
GISAID_background_fasta:
GISAID_background_metadata:
GISAID_background_expanded_metadata:
GISAID_background_expanded_fasta:

previous_uk_metadata:  # NEEDED IN STEP 1

latest_uk_fasta:
latest_uk_metadata:

uk_omissions:
uk_updated_dates:
uk_mask_file: /cephfs/covid/bham/raccoon-dog/resources/mask.txt

output_path: analysis
publish_path: publish
export_path: publish/phylogenetics

##### global lineage definitions #####
global_lineages:

##### Filter thresholds #####
min_covg: 93
min_length: 29000

##### Mapping reference #####
reference_fasta: /cephfs/covid/bham/raccoon-dog/grapevine/reference.fasta
reference_genbank_annotation: /cephfs/covid/bham/raccoon-dog/grapevine/MN908947.gb

##### Trim coordinates #####
trim_start: 265
trim_end: 29674

##### Files of variants to search for #####
snps: /cephfs/covid/bham/raccoon-dog/resources/snps.csv
dels: /cephfs/covid/bham/raccoon-dog/resources/dels.csv

##### File of lineages to split by #####
lineage_splits:
lineage_aliases:

##### Guide tree #####
guide_tree: /cephfs/covid/bham/raccoon-dog/resources/graft_guide.tree

##### Date #####
date:

##### Working directory #####
cwd:

##### Webhooks to push to #####
grapevine_webhook:
phylopipe_webhook:

##### report latex template #####
latex_template:
