##### Where is the data? #####

latest_majora_matched_fasta: input/elan.20210120.consensus.matched.fasta
latest_majora_matched_metadata: input/majora.20210120.metadata.matched.tsv
latest_uk_accessions: input/latest.accessions.tsv

uk_omissions: input/resequencing_omissions.txt
uk_updated_dates: input/date_corrections.csv
uk_mask_file: input/mask.txt

output_path: analysis
publish_path: publish
export_path: phylogenetics
json_path: webhook

##### global lineage definitions #####
uk_previous_pangolin_lineages: input/previous_pangolin_lineages.csv

##### Filter thresholds #####
min_covg: 50
min_length: 29000
# if a sample is older than this number of days before todays date, it will be excluded:
time_window: 25

##### Mapping reference #####
reference_fasta: .../grapevine/MN908947.fa
reference_genbank_annotation: .../grapevine/MN908947.gb

##### Trim coordinates #####
trim_start: 265
trim_end: 29674

##### Files of variants to search for #####
AAs: input/AAs.csv
dels: input/dels.csv
MINK_variants: input/MINK_AAs.txt

##### Date #####
date: 2021-01-20

##### Working directory #####
cwd:

##### Webhooks to push to #####
grapevine_webhook:
phylopipe_webhook:
phylopipe_token:

##### report latex template #####
latex_template:
