name: realtime-polio
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - biopython=1.74
  - coreutils=8.25
  - mafft
  - minimap2=2.17
  - pip=19.3.1
  - python=3.6
  - snakemake-minimal
  - pip:
    - git+https://github.com/cov-ert/datafunk.git@v0.0.0