name: grapevine
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - biopython=1.74
  - coreutils=8.25
  - iqtree=1.6
  - mafft
  - minimap2=2.17
  - pip=19.3.1
  - python=3.7.4
  - snakemake-minimal
  - pandoc=2.2.3.2
  - fasttree
  - pip:
    - git+https://github.com/cov-ert/datafunk.git
    - git+https://github.com/cov-ert/fastafunk.git
    - git+https://github.com/hCoV-2019/pangolin.git
    - git+https://github.com/hCoV-2019/spangolin.git
    - git+https://github.com/cov-ert/clusterfunk.git
    - git+https://github.com/hCoV-2019/lineages.git
    - git+https://github.com/cov-ert/Reports.git
    - git+https://github.com/neherlab/treetime
